[custom]
;基于ACL4SSR规则修改，仅保留ALL策略组

;设置规则标志位
ruleset=ALL,https://raw.githubusercontent.com/mphin/ProxyTools/main/rules/LocalAreaNetwork.list
ruleset=ALL,https://raw.githubusercontent.com/mphin/ProxyTools/main/rules/Google.list
ruleset=ALL,https://raw.githubusercontent.com/mphin/ProxyTools/main/rules/OpenaiNetflix.list
ruleset=ALL,https://raw.githubusercontent.com/mphin/ProxyTools/main/rules/ProxyMedia.list
ruleset=ALL,https://raw.githubusercontent.com/mphin/ProxyTools/main/rules/Microsoft.list
ruleset=ALL,https://raw.githubusercontent.com/mphin/ProxyTools/main/rules/Apple.list
ruleset=ALL,https://raw.githubusercontent.com/mphin/ProxyTools/main/rules/ChinaMedia.list
ruleset=ALL,https://raw.githubusercontent.com/mphin/ProxyTools/main/rules/GamesPlatform.list
ruleset=ALL,https://raw.githubusercontent.com/mphin/ProxyTools/main/rules/IpinfoSpeedtest.list
ruleset=ALL,https://raw.githubusercontent.com/mphin/ProxyTools/main/rules/Telegram.list
ruleset=ALL,https://raw.githubusercontent.com/mphin/ProxyTools/main/rules/ProxyGFWlist.list
ruleset=ALL,https://raw.githubusercontent.com/mphin/ProxyTools/main/rules/GlobalDirect.list
ruleset=ALL,[]GEOIP,CN
ruleset=ALL,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=ALL`select`[]DIRECT`.*
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true
